"""new mig

Revision ID: 1951f6b481ae
Revises: 559fcb38e87a
Create Date: 2023-02-19 16:12:46.197324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1951f6b481ae'
down_revision = '559fcb38e87a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
