"""new mig

Revision ID: 37a96f33efc9
Revises: 1951f6b481ae
Create Date: 2023-02-20 12:59:51.930600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = '37a96f33efc9'
down_revision = '1951f6b481ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_column('workspaces', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('workspaces', 'id')
    # ### end Alembic commands ###
