"""new mig

Revision ID: 559fcb38e87a
Revises: adfdec7856ba
Create Date: 2023-02-19 16:06:17.278542

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '559fcb38e87a'
down_revision = 'adfdec7856ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_column('workspaces', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('workspaces', 'uuid')
    # ### end Alembic commands ###
