"""new mig

Revision ID: ad7c3ffcc42b
Revises: 0a6ae39374e2
Create Date: 2023-02-17 02:14:58.535395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7c3ffcc42b'
down_revision = '0a6ae39374e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
