"""new mig

Revision ID: adfdec7856ba
Revises: ad7c3ffcc42b
Create Date: 2023-02-19 14:07:27.123395

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adfdec7856ba'
down_revision = 'ad7c3ffcc42b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_Workspace_id', table_name='Workspace')
    op.drop_table('Workspace')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workspace',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Workspace_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Workspace_pkey')
    )
    op.create_index('ix_Workspace_id', 'Workspace', ['id'], unique=False)
    op.drop_table('workspaces')
    # ### end Alembic commands ###
