"""new mig

Revision ID: d5797ea27d7c
Revises: d6c768b6cab9
Create Date: 2023-03-14 13:57:34.132812

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd5797ea27d7c'
down_revision = 'd6c768b6cab9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
